In [ ]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

In [ ]:
# Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [ ]:
# Make an RNN
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [ ]:
# Get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 206ms/step
[[0.29075414 0.38702232]]


In [ ]:
# See if we can replicate this output
# Get the weights first
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57 (228.00 Byte)
Trainable params: 57 (228.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# See what's returned
model.layers[1].get_weights()

[array([[-0.13039595,  0.78542644, -0.3094629 , -0.1366536 ,  0.7899415 ],
        [ 0.2932487 ,  0.46685857, -0.26400524, -0.6322343 , -0.79369545],
        [ 0.69740885, -0.32570374, -0.13433117,  0.70253867,  0.15324539]],
       dtype=float32),
 array([[ 0.6223297 , -0.14584102,  0.59675246,  0.10342678, -0.47394687],
        [ 0.13896014,  0.04645   , -0.5266    ,  0.7710713 , -0.32660988],
        [-0.30425715,  0.48190165, -0.09084556, -0.34898788, -0.7383447 ],
        [ 0.70504665,  0.39404568, -0.4256854 , -0.3611537 ,  0.1897293 ],
        [-0.06109637,  0.76751006,  0.42085388,  0.377528  ,  0.29588878]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [ ]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [ ]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [ ]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)

  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[0.29075417 0.38702241]


In [ ]:
# Bonus exercise: calculate the output for multiple samples at once (N > 1)